### ISSUE TITLE
Ignore script for logcheck to filter onioncat syslog messages

### ISSUE THREAD

**Issue by geebotron** [rahra/onioncat#1]
If you use logcheck to parse log files for interesting or unusual entries you might like this set of patterns for filtering onioncat log entries that are not really of note.

I put this in the file: `/etc/logcheck/ignore.d.server/local-rules`, which you will need to create if non-existent.

```
# onioncat
^[[:alpha:]]{3} [ :[:digit:]]{11} [._[:alnum:]-]+ onioncat\[[[:digit:]]+\]: \[(acceptor|connector|controller)\] select returned 0( fds ready)?$
^[[:alpha:]]{3} [ :[:digit:]]{11} [._[:alnum:]-]+ onioncat\[[[:digit:]]+\]: \[(acceptor|connector|controller|receiver)\] selecting \(maxfd = [[:digit:]]+\)$
^[[:alpha:]]{3} [ :[:digit:]]{11} [._[:alnum:]-]+ onioncat\[[[:digit:]]+\]: \[(acceptor|controller)\] setting up fd_set$
^[[:alpha:]]{3} [ :[:digit:]]{11} [._[:alnum:]-]+ onioncat\[[[:digit:]]+\]: \[(acceptor|connector|controller|receiver)\] timeout [[:digit:].]+$
^[[:alpha:]]{3} [ :[:digit:]]{11} [._[:alnum:]-]+ onioncat\[[[:digit:]]+\]: \[cleaner\] wakeup$
^[[:alpha:]]{3} [ :[:digit:]]{11} [._[:alnum:]-]+ onioncat\[[[:digit:]]+\]: \[main\] received on tunfd 4, framesize 48 \+ 4$
^[[:alpha:]]{3} [ :[:digit:]]{11} [._[:alnum:]-]+ onioncat\[[[:digit:]]+\]: \[main\] destination ff02::2 unreachable$
^[[:alpha:]]{3} [ :[:digit:]]{11} [._[:alnum:]-]+ onioncat\[[[:digit:]]+\]: \[main\] dropping frame$
^[[:alpha:]]{3} [ :[:digit:]]{11} [._[:alnum:]-]+ onioncat\[[[:digit:]]+\]: \[main\] reading from tunfd\[0\] = 4$
```

**Comment by rahra** [comment]
Most of these messages appear only if logging is set to debug level (7). You could simply lower the logging level. See option `-d` in the manpage.

**Comment by geebotron** [comment]
LOL. I thought the amount of log messaging was somewhat excessive!

**Comment by rahra** [comment]
If you would like to see incoming/outgoing connections you need -d 6. But actually you can completely deactivate it by setting -d 0. Most messages are only usefui for debugging and setup. E.g. in the Debian repository the default setting ist -d 0.

**Comment by rahra** [comment]
Yes, that's my man page. It's the everywhere same. But distros very often compile in a different way than the default package.
On Debian have a look at `/etc/default/onioncat`. There you will find the default options which is `-d 0`.

**Comment by geebotron** [comment]
Right. I was originally running it manually (as root) and omitting the '-d' flag.

**Comment by rahra** [comment]
You could edit the file `ocatsetup.c` in line number 55 and set the default log level `LOG_DEBUG` to something else (see `syslog(3)`) and recompile it.
