### ISSUE TITLE
How to use in Windows?

### ISSUE THREAD

**Issue by wmdfy** [rahra/onioncat#16]
How to use in Windows?

**Comment by rahra** [comment]
It worked fine to compile and run OnionCat on Windows with Cygwin at least on Windows 7. Since Windows has no native tunnel device it is necessary to install OpenVPN which comes with a Unix-compatible tap device. But I never tried on a more recent Windows versions mainly because I don't have such.

**Comment by wmdfy** [comment]
Good, I back to the test

**Comment by rahra** [comment]
Did you have any success?

**Comment by rahra** [comment]
I managed to compile a new binary version for Windows 10 and wrote an article here: https://www.onioncat.org/2019/08/onioncat-on-windows/
