### ISSUE TITLE
Automake

### ISSUE THREAD

**Issue by gh338** [rahra/onioncat#17]
make onioncat work with automake 1.16 or even more current versions - currently it requires 1.15 to ./configure and make

**Comment by rahra** [comment]
Run: `autotools -f`
It rebuilds all autotools files with your installed version. 

You need autotools only if you clone from here. With the released packages (https://www.cypherpunk.at/ocat/download/Source/current/) it is not necessary.

**Comment by gh338** [comment]
can't find autotools on my unbuntu 18.04/18.10...
apt-file search autotools also came up empty.

**Comment by rahra** [comment]
sorry, there was a typo: I modified my comment from above `autotools -f` -> `autoreconf -f`
The tool is found in the `autoconf` package (on Debian).

**Comment by gh338** [comment]
Working now.
Thank you
