### ISSUE TITLE
tunnel interface name prefix

### ISSUE THREAD

**Issue by gh338** [rahra/onioncat#18]
ocatun0 would fit nicely as tunx is mostly used by other apps already.

**Comment by rahra** [comment]
There already is the option -n which allow to choose a name for the tunnel device.
But this currently works just on Linux because tun device programming as a pain in the *ss in respect to portability...

**Comment by gh338** [comment]
The idea was merely to have the 'default' tunnel device name prefix as ocatun in the source ( to make it clear that this tunnel device is an onioncat device).
Thanks
