### ISSUE TITLE
ocat onion hostname shortening

### ISSUE THREAD

**Issue by gh338** [rahra/onioncat#19]
If it's not too much to ask can we have ocat 56charachterlong.onion on the cli to be internally cut down to the 16 actually used. 
This is just for convenience.

Thanks

**Comment by rahra** [comment]
I implemented this already but in a new branch https://github.com/rahra/onioncat/tree/hsv3_name since I was not able to test it thoroughly.

**Comment by gh338** [comment]
Will test it this week and report back.
Huge thanks !!!

**Comment by gh338** [comment]
Tested and working (ubuntu 18.04 + 18.10) with -H /etc/hosts on both sides.
