### ISSUE TITLE
i2p host mapping 

### ISSUE THREAD

**Issue by gh338** [rahra/onioncat#20]
i2p hostname resolution with -H does not work.
Even if the ipv6 .b32.i2p mapping in /etc/hosts is correct it fails for some reason and does NOT get to the point where it connects to the i2p socks service.
according to the ocat log ipv6 is requested correctly ( as mapped in /etc/hosts) but it fails with error 91.
i tried both notations 16digits.b32.i2p and 16digits.oc.b32.i2p without success
the i2p addressbook method still works wit 16digits.b32.i2p mapping

**Comment by rahra** [comment]
Error 91 indicates that the network (I2P) could not connect to the requested service.
Could you capture the SOCKS traffic (i.e. with wireshark) between OnionCat and I2P on the loopback adapter, to make sure that the mapping really is done correctly?

I dont't have any running I2P instance for the moment.

**Comment by rahra** [comment]
I just verified with 2 complete fresh I2P installation that it works as expected. Thus I assume there was/is something wrong in your setup.
Nevertheless, I just work on a new Howto for I2P these days.
