### ISSUE TITLE
Error: Nexthop device is not up

### ISSUE THREAD

**Issue by gh338** [rahra/onioncat#21]
First of all thanks for the overall updates !
With the latest git checkout b7828d221ce15b64350d6ca1abddb9400dce4310 i get this message:

/sbin/ip
Error: Nexthop device is not up.

onioncat is working fine though...

**Comment by rahra** [comment]
Ok, what OS do you use?
In ocattun.c, could you try to exchange lines 163 and 165 and recompile?
It may be that the route to the nexthop device is set before the link brought up.

**Comment by gh338** [comment]
done - now it just prints 

/sbin/ip

**Comment by rahra** [comment]
Ok, I'll push an update.
That's the code part which I'm not really proud of...

**Comment by gh338** [comment]
... you wrote onioncat ...

**Comment by rahra** [comment]
I completely rewrote the interface config mess for Linux now. It eliminates all shell command dependencies. 
For now it's found here in a new branch https://github.com/rahra/onioncat/tree/in6_ifreq
