### ISSUE TITLE
IP address configuration failure on Windows 10

### ISSUE THREAD

**Issue by friedkiwi** [rahra/onioncat#24]
OnionCat does not configure IP addresses correctly on Win10

Symptoms: 

    ping fd87:d87e:eb43:4506:3bbb:9faf:5877:4319
    
    Pinging fd87:d87e:eb43:4506:3bbb:9faf:5877:4319 with 32 bytes of data:
    PING: transmit failed. General failure. 
    PING: transmit failed. General failure.
    PING: transmit failed. General failure.
    PING: transmit failed. General failure.

Cause:

OnionCat tries to add a route to Windows 10 for the IPv6 addresses, however, no route is needed due to all addresses being in the same subnet. Correct approach would be to specify the subnet with the IP address setting.

I'll submit a PR soon with the changes.

**Comment by rahra** [comment]
First of all, thanks for submitting this patch!
These commands where figured out many years ago on a Win7, as far as I remember. Probably something changed since then.
Interestingly, last week I tested it on a Win10 because I wrote an article and I didn't encounter any problems but that may be just because I don't know exactly where to look at on Windows. I had to fiddle around with the network anyway, so probably I overlooked it.
I'll test your patch.

**Comment by friedkiwi** [comment]
I’ll fix the PR. 

My Windows 10 laptop has native IPv6 through LTE (in the UK, EE operates a V6-only network for data modems and offers NAT64), which might be what confused it. 

Are there any plans allocating an actual /48?

**Comment by rahra** [comment]
> Are there any plans allocating an actual /48?

You mean out of the public address space?
No, not really. What would be the advantage?
Actually, I think that this would introduce new risks in respect to anonymity. It is "private" network and shall connect systems privately. It's not intended to be reachable from the public.

**Comment by rahra** [comment]
The tunnel config code was completely rewritten. I incorporated your suggestion as well and I tested in on a Win10 machine. Meanwhile it's merged into master branch.
Can you confirm that the latest version works for you as well?

**Comment by rahra** [comment]
As to my best knowledge this problem is solved. Don't hesitate to reopen this issue again in case it reoccurs.
