### ISSUE TITLE
LLVM Clang compile warnings

### ISSUE THREAD

**Issue by grarpamp** [rahra/onioncat#26]
gcc 8.3.0 is clean
But maybe clang find some potential problems to improve.
onioncat 0.2.8 llvm clang 8.0.0 freebsd 12 x64

ocateth.c:282:24: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:282:44: warning: taking address of packed member 'ip6_dst' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:324:35: warning: taking address of packed member 'ip6_dst' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:324:84: warning: taking address of packed member 'ip6_dst' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:331:24: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:331:44: warning: taking address of packed member 'ip6_dst' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:342:33: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:349:25: warning: taking address of packed member 'nd_ns_target' of class or structure 'nd_neighbor_solicit' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:358:17: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:359:47: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:383:24: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:383:44: warning: taking address of packed member 'ip6_dst' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:409:17: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocateth.c:410:47: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocatipv4route.c:166:28: warning: size argument in 'strlcpy' call appears to be size of the source; expected the size of the destination [-Wstrlcpy-strlcat-size]
ocatipv6route.c:135:28: warning: size argument in 'strlcpy' call appears to be size of the source; expected the size of the destination [-Wstrlcpy-strlcat-size]
ocatroute.c:785:12: warning: taking address of packed member 'ip6_dst' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocatroute.c:944:19: warning: taking address of packed member 'ip6_dst' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
ocatroute.c:946:19: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]

**Comment by rahra** [comment]
Yes, I recognized this already. I'm always testing on OpenBSD, Linux, and FreeBSD. I ignored it so far ;) but of course I'll fix it.

**Comment by rahra** [comment]
Just to be a little bit more precise on that issue: That's not a problem, as long as you compile on architucres which allow unalligned pointers. E.g. on all x86 machines this is not a problem.

**Comment by rahra** [comment]
Pointer alignment fixed in 0e3f53bf5e4ad8948cc4d52f89c0ac584b827513.
