### ISSUE TITLE
hostname registration/lookup via .b32.i2p/.onion

### ISSUE THREAD

**Issue by gh338** [rahra/onioncat#27]
Would it be possible to autocalculate a .b32.i2p/.onion dest and then upload it to an i2p or tor service (manually configured / passed to ocat ) for central lookup ?
Just an idea to be able to deploy onioncat more widely.
The lookup service could be hosted and used by any volunteer - should be easy to do with i2p / tor.

**Comment by rahra** [comment]
Well, basically yes.
How exactly should that work?
Do you know that there is the option -e to run an ifup script. Actually this could be used to post something to somewhere, e.g. using curl.

Although there are millions of volunteers out there to produce all these quality open source products, as to my observation there are much fewer volunteers once it becomes to reliably run a service ;)

**Comment by rahra** [comment]
I just pushed an update (8468ae3). The environment now contains variables for the long and short URL.
Now you can run Onioncat with the option -e  pointing to your if-up script in which you could do something like this:
```
ip address add $OCAT_ADDRESS/$OCAT_PREFIXLEN dev $OCAT_IFNAME
ip link set $OCAT_IFNAME up 
ip route add table local $OCAT_PREFIX/$OCAT_PREFIXLEN dev $OCAT_IFNAME
curl "https://<your_onion_url.webserver>/?url=$OCAT_ONION_URL&url3=$OCAT_ONION3_URL&ip6=$OCAT_ADDRESS"
```

**Comment by gh338** [comment]
I will test and report back.
Thank you so much ! :-D

**Comment by rahra** [comment]
Did you have any success with your tests?

**Comment by rahra** [comment]
I close this now. IMO it works but don't hesitate to reopen it again, just in case.
