### ISSUE TITLE
no route to destination ff02::1:3, dropping frame

### ISSUE THREAD

**Issue by opiums9** [rahra/onioncat#30]
Hello! I want to try onioncat in a windows 7 VMware virtual machine. To set up onioncat, I used this instruction: https://www.onioncat.org/2019/08/onioncat-on-windows/.

I installed the TAP adapter from here: http://build.openvpn.net/downloads/releases/tap-windows-9.24.2-I601-Win7.exe
Rename adapter as "taplan".

Configured TOR:
```
DataDirectory C:\ProgramData\tor\Data\Tor
GeoIPFile C:\ProgramData\tor\Data\Torr\geoip
GeoIPv6File C:\ProgramData\tor\Data\Tor\geoip6
Log notice file C:\ProgramData\tor\Data\Tor\notice.log
#Socks5Proxy 127.0.0.1:8119
HTTPTunnelPort 8118

HiddenServiceDir C:\ProgramData\tor\Site\onioncat_hsv2
HiddenServiceVersion 2
HiddenServicePort 8060 127.0.0.1:8060
HiddenServiceDir C:\ProgramData\tor\Site\onioncat_hsv3
HiddenServiceVersion 3
HiddenServicePort 8060 127.0.0.1:8060

SocksListenAddress 0.0.0.0
SocksPort 0.0.0.0:9999
SocksPort 0.0.0.0:9150
#SocksPolicy accept 10.0.0.0/8
#SocksPolicy accept 192.0.0.0/8
#SocksPolicy accept 127.0.0.0/8
#SocksPolicy reject *
```

I downloaded and unpacked onioncat, launched it with the following parameters in cmd:
`"%cd%\ocat_debug.exe" -L ocat.log -4 -t 9150 -U aqoidrlyym3gpntr.onion`

But my adapter is not getting the address and apparently the routes are not working, what am I doing wrong?
ocat.log: https://gist.github.com/opiums9/7410ba700bd179d57a0d2c3ad643b9af

**Comment by rahra** [comment]
Are you sure that it is not working? According to your log it looks fine.
Did you try to locally ping your OnionCat address as well as the "dead-beef" (`fd87:d87e:eb43::dead:beef`) and the "feed-beef" (`fd87:d87e:eb43::feed:beef`) address?

**Comment by rahra** [comment]
BTW, you can safely ignore the message `no route to destination ff02::1:3, dropping frame`. This is because multi-casting isn't possible in the OC network but the OS does not know about this, hence, it still sends such packets to the OC tunnel interface.

**Comment by opiums9** [comment]
My problem was that it was necessary to write the address in the adapter, otherwise it was on an unknown network, thx
