### ISSUE TITLE
Onioncat spitting error, windows 10 config

### ISSUE THREAD

**Issue by mato200** [rahra/onioncat#35]
Pls help, i followed this guide https://www.onioncat.org/2019/08/onioncat-on-windows/
I configured everything, even tried with v3, launched Tor, launched onioncat shortcut with correct paramiters and i get this:

Thu, 14 Oct 2021 12:39:22.541 +0200 [0:main      :  info] onioncat 0.3.8 (c) Bernhard R. Fischer (OnionCat mode)
Thu, 14 Oct 2021 12:39:22.543 +0200 [0:main      :  info] MAC address (censored by me in edit)
Thu, 14 Oct 2021 12:39:22.544 +0200 [0:main      :  info] IPv6 address  (censored by me in edit)
Thu, 14 Oct 2021 12:39:22.545 +0200 [0:main      :  info] TUN/TAP device Local Area Connection 2
Thu, 14 Oct 2021 12:39:22.564 +0200 [0:main      :warning] can't get information for user "tor": "user not found", defaulting to uid 65534
Thu, 14 Oct 2021 12:39:22.565 +0200 [0:main      :notice] disabling connect log
Thu, 14 Oct 2021 12:39:22.577 +0200 [0:main      :  info] starting packet forwarder
Thu, 14 Oct 2021 12:39:22.577 +0200 [2:acceptor  :  info] connection 10 [0] accepted on listener 5 from 127.0.0.1 port 9563
Thu, 14 Oct 2021 12:39:22.578 +0200 [0:main      :   err] no route to destination ff02::1:2, dropping frame.
Thu, 14 Oct 2021 12:39:22.579 +0200 [2:acceptor  :  info] inserting peer fd 10 to active peer list
Thu, 14 Oct 2021 12:39:22.589 +0200 [1:receiver  :  info] incoming connection on 10 from  (censored by me in edit) is now identified
Thu, 14 Oct 2021 12:39:22.685 +0200 [6:lloopback :  info] loopback_handler ready listening on  (censored by me in edit)
Thu, 14 Oct 2021 12:39:22.861 +0200 [0:main      :   err] no route to destination ff02::2, dropping frame.
Thu, 14 Oct 2021 12:39:22.864 +0200 [0:main      :   err] no route to destination ff02::16, dropping frame.
Thu, 14 Oct 2021 12:39:23.354 +0200 [0:main      :   err] no route to destination ff02::16, dropping frame.
Thu, 14 Oct 2021 12:39:23.561 +0200 [0:main      :   err] no route to destination ff02::1:2, dropping frame.
Thu, 14 Oct 2021 12:39:23.866 +0200 [0:main      :   err] no route to destination ff02::16, dropping frame.
Thu, 14 Oct 2021 12:39:23.868 +0200 [0:main      :   err] no route to destination ff02::fb, dropping frame.
Thu, 14 Oct 2021 12:39:23.869 +0200 [0:main      :   err] no route to destination ff02::fb, dropping frame.
Thu, 14 Oct 2021 12:39:23.870 +0200 [0:main      :   err] no route to destination ff02::16, dropping frame.
Thu, 14 Oct 2021 12:39:23.871 +0200 [0:main      :   err] no route to destination ff02::fb, dropping frame.
Thu, 14 Oct 2021 12:39:23.872 +0200 [0:main      :   err] no route to destination ff02::fb, dropping frame.
Thu, 14 Oct 2021 12:39:24.351 +0200 [0:main      :   err] no route to destination ff02::16, dropping frame.
Thu, 14 Oct 2021 12:39:25.571 +0200 [0:main      :   err] no route to destination ff02::1:2, dropping frame.
Thu, 14 Oct 2021 12:39:25.860 +0200 [0:main      :   err] no route to destination ff02::16, dropping frame.
Thu, 14 Oct 2021 12:39:25.862 +0200 [0:main      :   err] no route to destination ff02::16, dropping frame.
Thu, 14 Oct 2021 12:39:25.866 +0200 [0:main      :   err] no route to destination ff02::16, dropping frame.
Thu, 14 Oct 2021 12:39:25.867 +0200 [0:main      :   err] no route to destination ff02::16, dropping frame.
Thu, 14 Oct 2021 12:39:25.869 +0200 [0:main      :   err] no route to destination ff02::fb, dropping frame.
Thu, 14 Oct 2021 12:39:25.870 +0200 [0:main      :   err] no route to destination ff02::fb, dropping frame.
Thu, 14 Oct 2021 12:39:25.871 +0200 [0:main      :   err] no route to destination ff02::fb, dropping frame.
Thu, 14 Oct 2021 12:39:25.872 +0200 [0:main      :   err] no route to destination ff02::fb, dropping frame.

**Comment by rahra** [comment]
Everything looks fine.
You can ignore all `no route to destination ff02::fb, dropping frame.` errors. This is Windows trying to send out multi-cast packets which does not work with OC since it is not a multi-cast-aware network.

Did you try to ping the test responders? (`fd87:d87e:eb43::dead:beef` and `fd87:d87e:eb43::feed:beef`)

**Comment by rahra** [comment]
Can you please open a `cmd` window and list the network interfaces with `ipconfig /all`, to make sure the interface is there and properly configured. There should be "TAP Windows Adapter V9" having your OnionCat IPv6 address assigned.
You can also make a `netstat -nr` which shall show a route to the OC network (`fd87:d87e:eb43::/48`).
I think this is some kind of "Windows problem" with firewall, virus scanner, or similar, since OnionCat did not issue any relevant error message.
Another issue could be that you used OpenVPN adapter version 2.5.x. Something was changed and it does not work. You have to use the OpenVPN adapter version 2.4.x. Although I think OC would have failed to start as far as I remember.

**Comment by mato200** [comment]
In CMD, TAP windows adapter shows different IPv6 address thant the Ocat log

**Comment by mato200** [comment]
when i tun netstat - nr  there is no fd87:d87e:eb43::/48 showing anywhere


IPv6 Route Table
===========================================================================
Active Routes:
 If Metric Network Destination      Gateway
  1    331 ::1/128                  On-link
  4    291 fe80::/64                On-link
 25    291 fe80::/64                On-link
 20    281 fe80::/64                On-link
 15    311 fe80::/64                On-link
 20    281 fe80::CENS:ORED:CENS:ORED/128
                                    On-link
 15    311 fe80::CENS:ORED:CENS:ORED/128
                                    On-link
 25    291 fe80::CENS:ORED:CENS:ORED/128
                                    On-link
  4    291 fe80::CENS:ORED:CENS:ORED/128
                                    On-link
 15    311 fec0::/64                On-link
 15    311 fec0::CENS:ORED:CENS:ORED/128
                                    On-link
  1    331 ff00::/8                 On-link
  4    291 ff00::/8                 On-link
 25    291 ff00::/8                 On-link
 20    281 ff00::/8                 On-link
 15    311 ff00::/8                 On-link
===========================================================================
Persistent Routes:
  None

**Comment by rahra** [comment]
seems to be fixed, closing.
