### ISSUE TITLE
Torifying Wireguard

### ISSUE THREAD

**Issue by OliverOffing** [rahra/onioncat#36]
Hi, I'm interested in the use-cases that onioncat looks to address. I was just wondering if you've ever considered using `torify` plus `wireguard` (or `openvpn` for that matter) as means to achieve the same result?

The "simple" implementation might involve having the server have a clearnet IP address, and the traffic come out of Tor Exit Nodes. The "advanced" implementation would be of course to hide all IP addresses by using Tor Hidden Services, which would make the traffic never leave the Tor network and I guess would increase network speeds.

Here's an example using [wireguard + shadowsocks](https://github.com/rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs/issues/17). It's not tor but it's a SOCKS proxy, which tor provides.

Looking forward to hearing your thoughts.

**Comment by rahra** [comment]
Hi Oliver,

OnionCat is a server-less peer-to-peer VPN. It is a VPN in its original sense, not what some non-IT-people today understand under the term "VPN", as being a service for "safely" browsing the web.
OnionCat does never exit, it is based on hidden services. 
OnionCat comes with a dynamic method of addressing which basically eliminates the need for any configuration and IP/routing setup. Although the version 3 of Tor's hidden services (HSv3) broke this method of addressing, new features were implemented during the last year to re-enable this again. I'm currently working on an article which will explain how these new features for HSv3 work.

**Comment by OliverOffing** [comment]
Hi Bernard,

Thank you for your response. What you're saying makes total sense and specifically the fact that OnionCat basically does away with IP/routing is a feature I had overlooked. After experimenting with ZeroTier, WireGuard, Tor Hidden Services, and I2P, I'm delighted to say I've circled back to OnionCat. Looking forward to what you have in store.

Closing this issue now—thank you.
