### ISSUE TITLE
onioncat works on OpenBSD

### ISSUE THREAD

**Issue by ZhanYF** [rahra/onioncat#37]
I noticed this line on the TODO list:
* OpenBSD TAP device might not work (see OpenBSD man page tun(4))

and I think I should report back that this works fine on OpenBSD :)

I used onioncat on OpenBSD with ping and ssh as payload, and there is no problem so far.

**Comment by rahra** [comment]
Oh, thank you very much!
I think I should update this list. I think I didn't update it at least since 10 years ;)

**Comment by rahra** [comment]
TODO slightly updated
