### ISSUE TITLE
Torrc configuration isn't working. Not allowing tor browser bundle to Connect? (Win 10)

### ISSUE THREAD

**Issue by conhibit** [rahra/onioncat#39]
![image](https://user-images.githubusercontent.com/100077031/196030994-ad216534-0f80-444d-9918-69de2946f87f.png)
this pic should explain it... i click retry and then tor gets stuck on connecting... forever.

No onioncat logs are created... I think the problem may be from entering the wrong directory to save the Logs possibly... also whenever i delete tor and reinstall it gives this error unless i start without pasting the onioncat log configs in...

Maybe its a firewall issue?

**Comment by rahra** [comment]
Most probably it is because of the HSv2 service in your config. Support was dropped some time ago.
Remove it from your config and retry.

**Comment by rahra** [comment]
I assume that this issue is resolved.
