### ISSUE TITLE
Could onioncat theoretically be connected through any network that exposes a SOCKS proxy and uses .onion-style hostnames?

### ISSUE THREAD

**Issue by janicez** [rahra/onioncat#4]
I just thought I'd ask a strictly theoretical question about onioncat.

if I ran a socks proxy that accepts old-version onion-shaped addresses like tor does and translates them its own way, could i make it connect to an onioncat on the other end through a network other than Tor or i2p?

**Comment by rahra** [comment]
Yes, definitively.
SOCKS4A is used which means that the (.onion) name resolution is done by the SOCKS proxy (which usually is Tor). Thus, if you ensure that the SOCKS proxy can resolve .onion – as mentioned in the subject – it will work.

**Comment by janicez** [comment]
that's what i wanted to know. it doesn't matter if the proxy isn't tor, right?

**Comment by rahra** [comment]
Yes, it does not care. You can use it with any SOCKS4A-Proxy.

**Comment by rahra** [comment]
Q is considered to be answered satisfyingly.
