### ISSUE TITLE
How do I generate some new Hostnames in the hostname file after I get the first one called '-a' ?

### ISSUE THREAD

**Issue by conhibit** [rahra/onioncat#40]
im guessing i got to keep reconnecting Tor and check the Hostname file in notepad? 

im of course talking about the one in:
/var/lib/tor/onioncat_hsv3 

![image](https://user-images.githubusercontent.com/100077031/196381123-be9cf762-a264-4958-8087-f3494301dc5f.png)

not sure yet why i need more of them than 1 but im assuming they offer me different ip's to use or something : /

**Comment by rahra** [comment]
Sorry for late answer.
It highly depends on your use-case.
You should read this article (https://github.com/rahra/onioncat/blob/master/doc/INTRO_TO_ONIONCAT4.txt) which shall explain everything about the latest version of OnionCat4.

**Comment by rahra** [comment]
I assume that the question was answered. Please don't hesitate to reopen this again.
