### ISSUE TITLE
Obsolete in tree freebsd port

### ISSUE THREAD

**Issue by ZhanYF** [rahra/onioncat#41]
The in tree freebsd port directory is from 10+ years ago, perhaps it can be removed to prevent possible confusion?
Onioncat has been imported and maintained in the freebsd port tree for many years.

**Comment by rahra** [comment]
Yes, you are right. There are other things in the tree which should be cleanup as well...
I'll do so.

**Comment by rahra** [comment]
I removed it in the dev branch with commit a54a54b0dc8acac6eaad801f543be99ca6f8d958 .
I will soon merge it into master but I'm working on an issue within the dev code.
