### ISSUE TITLE
Onioncat tries to create localstatedir outside of DESTDIR

### ISSUE THREAD

**Issue by badshah400** [rahra/onioncat#43]
This came up when I was trying to update onioncat packages for openSUSE from version 0.3.9 to 4.10.0.

With version 4.10.0, the build system of onioncat tries to install the `oc_statedir` into ${prefix}/var outside of DESTDIR (commit 1e3034a12d793330775b74ab76e7d92d09efc61b). This is a problem in particular when building RPM packages because we compile and install the package with DESTDIR set to a buildroot directory and then package whatever is installed to the buildroot dir in the form of RPMs. Perhaps this is also a problem more generally for folks who would want to install onioncat to some non-standard location using DESTDIR.

Fixed by a one-liner (can make a PR if you want me to):

```diff
Index: onioncat-4.10.0/src/Makefile.am
===================================================================
--- onioncat-4.10.0.orig/src/Makefile.am
+++ onioncat-4.10.0/src/Makefile.am
@@ -5,5 +5,5 @@ oc_statedir = $(localstatedir)/onioncat
 AM_CFLAGS = -DSYSCONFDIR=\"$(sysconfdir)\" -DSTATEDIR=\"$(oc_statedir)\"
 
 install-data-hook:
-	$(MKDIR_P) $(oc_statedir)
+	$(MKDIR_P) $(DESTDIR)$(oc_statedir)
```

Thanks for developing this very useful application.

**Comment by rahra** [comment]
Ok, thanks for reporting. I'll check it and update it soon.

**Comment by rahra** [comment]
Works.
Commited in cf750e57d2cd79feb78ea3c71ddf19f9fb05ed77 .

**Comment by badshah400** [comment]
Many thanks for the quick follow-up.
